name: Issue Close Inactive

on:
  schedule:
    # GMT+8 00:00
    - cron: '0 19 * * *'
  issues:
      types: [labeled]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: 'inactive'
          inactive-day: 3
          body: |
            Since the issue was labeled with `${{github.event.label.name}}`, but no response in 3 days. This issue will be closed. If you have any questions, you can comment and reply.
            由于该 issue 被标记为`${{github.event.label.name}}`，却 3 天未收到回应。现关闭 issue，若有任何问题，可评论回复.

  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - name: lock-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issues'
          token: ${{ secrets.GITHUBTOKEN }}
          issue-state: closed
          inactive-day: 14
          body: |
            This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

            此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          inactive-day: 3
